openapi: 3.0.3
info:
  title: STD23084 - TD1
  description: there are the specifications of my API
  version: 1.1.0
servers:
  - url: 'https://localhost.STD23084.com'
paths:
  /customers:
      get:
        summary: returns a list of customers
        parameters:
          - name: page
            required: true
            description: the page index
            in: query
            schema:
              type: integer
          - name: pageSize
            description: the number of page
            required: true
            in: query
            schema:
              type: integer
              example: 1000


        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                 type: array
                 items:
                  $ref: "#/components/schemas/Customer"
      post:

        summary: add a new customer to database
        operationId: addCustomer`w  ahj"
        requestBody:
          content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Customer'
                application/xml:
                  schema:
                    $ref: '#/components/schemas/Customer'
                application/x-www-form-urlencoded:
                  schema:
                    $ref: '#/components/schemas/Customer'
          required: true
        responses:
          '200':
              description: customer added to database !
  /Meal :
    get :
      summary: return the list of meals
      parameters:
        - name : page
          description: the page
          required: true
          in: query
          schema:
            type: integer
            example: 3456
        - name: pageSize
          description: the number of page
          required: true
          in: query
          schema:
            type: integer
            example: 1000
      operationId: getAllMeals

      responses:
        200:
          description: Success !
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Meal"










components:
  schemas:
          Customer:
            type: object
            properties:
              name:
                type: string
                example: kyle
              age:
                type: integer
                example: 18
              id:
                type: string
                example: "123456787SDFGFDFGHDFG"
          Meal :
            properties:
              name :
                type: string
                example: "patate"
              price:
                type : number
                format: double
          PersonneAvecAdresse:
            type: object
            properties:
              nom:
                type: string
              age:
                type: integer
              rue:
                type: string
              ville:
                type: string







  
