openapi: 3.0.3
info:
  title: STD23084 - TD1
  description: there are the specifications of my API
  version: 1.0.0
servers:
  - url: 'https://localhost.STD23084.com'
paths:
  /customers:
      get:
        summary: returns a list of customers
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                 type: array
                 items:
                  $ref: "#/components/schemas/Customer"
components:
  schemas:
          Customer:
            type: object
            properties:
              name:
                type: string
                example: kyle
              age:
                type: integer
                example: 18





  
